# Generated by Django 5.2 on 2025-04-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField()),
                ('years_of_exp', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Technician',
        ),
    ]
