# Generated by Django 5.2 on 2025-04-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_technicianqualification_delete_technician'),
        ('guest', '0003_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianqualification',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.customer'),
        ),
    ]
