# Generated by Django 5.2 on 2025-04-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer_address', 'verbose_name_plural': 'customer_addresss'},
        ),
    ]
