# Generated by Django 5.2 on 2025-05-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_alter_customer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('technician', 'Technician')], default='user', max_length=255),
        ),
    ]
