# Generated by Django 5.2 on 2025-05-05 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0005_technicianqualification_customer'),
        ('guest', '0003_alter_customer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.customer')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.issue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.product')),
            ],
        ),
    ]
