# Generated by Django 5.2 on 2025-05-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending'),
        ),
    ]
