# Generated by Django 5.2 on 2025-05-07 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_technicianqualification_customer'),
        ('user', '0002_alter_service_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('service_address', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.service')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.technicianqualification')),
            ],
        ),
    ]
